[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["utils/**"]
  external_node_modules = ["node-cache"]
  # Set timeout to 30 seconds (maximum allowed by Netlify)
  timeout = "30"

[dev]
  framework = "#static"
  targetPort = 3999
  port = 8888
  publish = "public"
  # Setup a netlify.toml file with a [dev] section to specify your dev server settings.
  # See docs at: https://docs.netlify.com/cli/local-development/#project-detection
  # test

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[headers]]
  for = "/api/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
    Access-Control-Allow-Credentials = "true"
    Vary = "Origin"
